[versions]
agp = "8.4.1"
kotlin = "2.0.0"
java = "1.8"

sdk-compile = "34"
sdk-min = "21"
sdk-target = "34"
ndk = "26.3.11579264"

androidx-annotation = "1.8.0"
androidx-appcompat = "1.7.0"
androidx-constraintlayout = "2.1.4"
androidx-core = "1.13.1"
androidx-fragment = "1.7.1"
androidx-preference = "1.2.1"
androidx-recyclerview = "1.3.2"
androidx-swiperefreshlayout = "1.1.0"

checkstyle = "10.17.0"
commons-lang = "3.14.0"
commons-text = "1.12.0"
google-flexbox = "3.0.0"
google-material = "1.12.0"
jackson = "2.17.1"
jdk-desugar = "2.0.4"
kotlinx-datetime = "0.6.0"
kotlinx-serialization = "1.6.3"
media3 = "1.3.1"
netcipher = "2.1.0"
okhttp = "4.12.0"
pmd = "6.55.0"
zstd = "1.5.6-3"

junit = "4.13.2"
androidx-test-core = "1.5.0"
androidx-test-espresso = "3.5.1"
androidx-test-rules = "1.5.0"
androidx-test-junit = "1.1.5"

compose-bom = "2024.06.00"
androidx-compose-constraintlayout = "1.0.1"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "androidx-fragment" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "androidx-preference" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }

commons-lang = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }
google-flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "google-flexbox" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jdk-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "jdk-desugar" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json-okio = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-okio", version.ref = "kotlinx-serialization" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
netcipher-webkit = { module = "info.guardianproject.netcipher:netcipher-webkit", version.ref = "netcipher" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
zstd = { module = "com.github.luben:zstd-jni", version.ref = "zstd" }

junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "androidx-test-espresso" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref="androidx-compose-constraintlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
